<?php
function chess_menu(){
  $items ['chess']= array(
    'title' =>'',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chess_new_game_form'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'user_is_logged_in',
  ) ;
  $items ['chess/game'] = array(
    'title' => 'Chess',
    'page callback' => 'chess_game',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'user_is_logged_in',
  );
  $items ['chess/game/move'] = array(
    'title' => '',
    'page callback' => 'chess_move',
    'type' => MENU_CALLBACK,
    'access callback' => 'user_is_logged_in',
    'file' => 'includes/chess.move.inc',
  );
  return $items;
}
function chess_new_game_form($form,$form_state){
  $form['chess_figure'] = array(
    '#type' => 'select',
    '#title' => t('chess figure'),
    '#default_value' => variable_get('chess_figure','3'),
    '#options' => array(
      'pawn' => t('pawn'),
      'castle' => t('castle'),
      'knight' => t('knight'),
    ),
    '#description'=> t('selection chess figure'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#weigth' => 50,
    '#value' => t('Create new game'),
  );
  $form['#submit'] = array('chess_new_game_submit');
  return $form;
}
function chess_new_game_submit($form,&$form_state){
  $values = array(
    'type' => $form_state['values']['chess_figure'],
    'color'=> 'black',
    'cell_x' => 1,
    'cell_y' => 1,
  );
  $figure = entity_get_controller('chess_figure')->create($values);
  $figure->save();
  $form_state['redirect'] = 'chess/game';

}