<?php
module_load_include('inc','chess_figure','includes/forms/chess_figure_form');
module_load_include('inc','chess_figure','includes/forms/chess_figure_type_form');

module_load_include('inc','chess_figure','includes/chess_figure_function');


/**
 *  Implements hook_entity_info().
 */
function chess_figure_entity_info() {
  $info['chess_figure'] = array(
    'label' => t('Chess figure'),
    'plural label' => t('Chess figures'),
    'entity class' => 'ChessFigure',
    'controller class' => 'ChessFigureController',
    'views controller class' => 'EntityDefaultViewsController',
    'metadata controller class' => 'ChessFigureMetadataController',
    'base table' => 'chess_figure',
    'fieldable' => TRUE,
    'statusKey' => NULL,
    'translation' => array(
      'entity_translation' => array(
        'class' => 'EntityTranslationDefaultHandler',
        'base path' => 'chess/figure/%chess_figure',
      ),
    ),

    'entity keys' => array(
      'id' => 'fid',
      'bundle' => 'type',
    ),
    'load hook' => 'chess_figure_load',
    'uri callback' => 'chess_figure_uri',
    'access callback' => 'chess_figure_access',
    'module' => 'chess_figure',
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'view modes' => array(
      'description' => array(
        'label' => t('Description'),
        'custom settings' => TRUE,
      ),
      'on_board' => array(
        'label' => t('On board'),
        'custom settings' => TRUE,
      ),
    ),
    'bundles' => array(),
  );

  $types = db_select('chess_figure', 'c')
    ->fields('c')
    ->execute()
    ->fetchAllAssoc('type');

  foreach ($types as $type => $info_type_figure) {
    $info['chess_figure']['bundles'][$type] = array(
      'label' => $info_type_figure->label, //мітку прсвоемо из бази даних
      'admin' => array(
        'path' => 'admin/structure/chess/figure/%chess_figure_type',
        //шлях за яким буде доступна наша сутність
        'real path' => 'admin/structure/chess/figure/' . $type,
        // реальний шлях до сутності
        'bundle argument' => 4,
        //аргумент в якому передаеться тип сутності
        'access arguments' => array('administer chess figure'),
        //аргумент доступу до підтипу
      ),

    );
  };

  $info['chess_figure_type'] = array(
    'label' => t('Chess figure type'),
    'controller class' => 'ChessFigureTypeController',
    'entity class' => 'ChessFigureType',
    'base table' => 'chess_figure_type',
    'static cache' => FALSE,
    'field cache' => FALSE,
    'uri callback' => 'chess_figure_uri',
    'fieldable' => TRUE,
    'bundle of' => 'chess_figure',
    'exportable' => FALSE,
    'entity keys' => array(
      'id' => 'tid',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'chess_figure_access',
    'module' => 'chess_figure',
    'admin ui' => array(
      'path' => 'admin/structure/chess/figure',

      'controller class' => 'ChessFigureTypeUIController',
    ),

  );


  return $info;
}


/**
 *  Implements hook_permission().
 */
function chess_figure_permission() {
  return array(
    'administer chess figure' => array(
      'title' => t('administer chess figure'),
      'description' => t('administer chess figure.'),
      'restrict access' => FALSE,
    ),
    'administer own chess figure' => array(
      'title' => t('administer own chess figure'),
      'description' => t('administer own chess figure.'),
      'restrict access' => TRUE,
    ),
  );
}

function chess_figure_menu(){
  $items['chess/figure'] = array(
    'title' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chess_figure_form'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' =>'user_is_logged_in',
  );

  $items['chess/figure/%'] = array(
    'title'=>'',
    'page callback' => 'chess_figure_on_board',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 *  Implements hook_theme().
 */
function chess_figure_theme() {
  return array(
    'chess_figure' => array(
      'template' => 'theme/chess_figure',
      'variables' => array(
        'cell' => NULL,
        'color' => NULL,
        'type' => NULL,
      ),
      ),
  );
}

function chess_figure_on_board($id){
  $chess_figure = chess_figure_load($id);

  $values = array(
    'cell' => ('' . $chess_figure->cell_x . $chess_figure->cell_y),
    'color' => $chess_figure -> color,
    'type' => $chess_figure -> type,
  );
  return theme('theme/chess_figure',$values);
}


