<?php
module_load_include('inc','chess_figure','includes/classes/ChessFigure');
module_load_include('inc','chess_figure','includes/classes/ChessFigureController');
module_load_include('inc','chess_figure','includes/classes/ChessFigureMetaDataController');

module_load_include('inc','chess_figure','includes/classes/ChessFigureType');
module_load_include('inc','chess_figure','includes/classes/ChessFigureTypeController');
module_load_include('inc','chess_figure','includes/classes/ChessFigureTypeMetaDataController');

module_load_include('inc','chess_figure','includes/classes/ChessFigureUI');

module_load_include('inc','chess_figure','includes/classes/ChessFigureTypeUI');

module_load_include('inc','chess_figure','includes/forms/chessFigureForm');
module_load_include('inc','chess_figure','includes/forms/chessFigureTypeForm');

module_load_include('inc','chess_figure','includes/hooks/entityInfo');
module_load_include('inc','chess_figure','includes/hooks/permission');
module_load_include('inc','chess_figure','includes/hooks/menu');

module_load_include('inc','chess_figure','includes/chessFigureFunction');